### ISSUE TITLE
Allow keyboard Commands for Markdown Syntax and allow tables and footnotes

### ISSUE THREAD

**Issue by Ravenb23** [chigkim/AME#3]
Hi there.
I’ve been a user of AME for a while and I absolutely love it. This request covers two separate things.
1. Is it possible to assign key commands to certain markdown syntax. For example, Alt+CTRL+1 adds in one # for heading level 1.
2.  Is there anyway to add support for other syntax such as tables and footnotes. I may be doing something incorrectly, but every time I try to use markdow for a footnote or table, it doesn’t show up correctly in the HTML view.
Thank you in advance for your consideration.

**Comment by chigkim** [comment]
I updated markdown module, and enabled extra extension.
https://github.com/chigkim/AME/releases/tag/v0.1.1
For syntax, check out this documentation.
https://python-markdown.github.io/extensions/extra/
I'll think about the keyboard shortcut in the future.
This is just a pet project I worked on mainly for me to learn WXPython, and I don't have a bandwidth at the moment unfortunately.
